modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="cobe"
version="1"
displayName="Cobe"
logoFile="icon.png"
authors="Akaize"
description="""
geckolib the best! 
 built-in : javacv,opencv,ffmpeg"""

[[dependencies.cobe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cobe]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

