{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "cobe-fabric-linux",
    "version": "1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cobe-fabric-linux-1.jar",
          "url": "cobe-fabric-linux-1.jar",
          "size": 100302,
          "sha512": "9697975393a18d6b7ff4b62d0b86805fbb3a79a212005513423a26733f27e6846182af4e6c72fd570647537c340f9c53d90b180f197c7e2b5363698e5806b5f4",
          "sha256": "2f57334384178b1a922b5372132ed52b33d36e0c44148fc1b8b66e1127c495d1",
          "sha1": "3e149ed59c9b671a20a818368b15184a4fa11b99",
          "md5": "ebf9a26ddb8416b924fb802c10e4417b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "v.akfz",
          "module": "aslib-fabric",
          "version": {
            "requires": "Dev_1.20.1-SNAPSHOT"
          }
        },
        {
          "group": "org.bytedeco",
          "module": "javacpp",
          "version": {
            "requires": "1.5.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javacpp",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "org.bytedeco",
          "module": "ffmpeg",
          "version": {
            "requires": "6.1.1-1.5.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ffmpeg",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "org.bytedeco",
          "module": "javacv",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        }
      ],
      "files": [
        {
          "name": "cobe-fabric-linux-1.jar",
          "url": "cobe-fabric-linux-1.jar",
          "size": 100302,
          "sha512": "9697975393a18d6b7ff4b62d0b86805fbb3a79a212005513423a26733f27e6846182af4e6c72fd570647537c340f9c53d90b180f197c7e2b5363698e5806b5f4",
          "sha256": "2f57334384178b1a922b5372132ed52b33d36e0c44148fc1b8b66e1127c495d1",
          "sha1": "3e149ed59c9b671a20a818368b15184a4fa11b99",
          "md5": "ebf9a26ddb8416b924fb802c10e4417b"
        }
      ]
    }
  ]
}
