{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "cobe-common-linux",
    "version": "1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cobe-common-linux-1.jar",
          "url": "cobe-common-linux-1.jar",
          "size": 98408,
          "sha512": "63e16a67f5b64ecff6c528f231490c868d07d9403bf0d70b9cb7f6c821697e4c9b444a629643997657550cd1957c6712296fa7b620063221cfa8ba136bda2255",
          "sha256": "bd1018615f30becd936e19cbd15ec624972256f4376a5b48a84e0b8b8967d353",
          "sha1": "4dd00f65cd2240363bd01e8bcb1a76059211ec48",
          "md5": "81c2f3489ce95c4c39b3417d00d2ffd3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "v.akfz",
          "module": "aslib-common",
          "version": {
            "requires": "Dev_1.20.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cobe-common-linux-1.jar",
          "url": "cobe-common-linux-1.jar",
          "size": 98408,
          "sha512": "63e16a67f5b64ecff6c528f231490c868d07d9403bf0d70b9cb7f6c821697e4c9b444a629643997657550cd1957c6712296fa7b620063221cfa8ba136bda2255",
          "sha256": "bd1018615f30becd936e19cbd15ec624972256f4376a5b48a84e0b8b8967d353",
          "sha1": "4dd00f65cd2240363bd01e8bcb1a76059211ec48",
          "md5": "81c2f3489ce95c4c39b3417d00d2ffd3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cobe-common-linux-1-sources.jar",
          "url": "cobe-common-linux-1-sources.jar",
          "size": 48804,
          "sha512": "787177497f6d2f3941362b6c597878febff1932c17dea6f5e33631b0c2c2c29a5757e521886dae24e55c6bc90273b448ac7fe3b9d9fec0ec35980a116801a09e",
          "sha256": "44396a3097cd88a066ee6c4e34adafc80699bc0870e7c069f2bb351b7ab0d407",
          "sha1": "b85328a5f974350bfcf063236bb7336379d9abc8",
          "md5": "78d30bb0b06c021fab0ceaa8659133f9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cobe-common-linux-1-javadoc.jar",
          "url": "cobe-common-linux-1-javadoc.jar",
          "size": 315253,
          "sha512": "e4aa80d13a89134e0cc95bf127b558275e2c0383e522f5b236f7c984468118e69edadef2aa4c291a9f152657aaa4c239d6c0e97ada000d221b116fd8249a05c1",
          "sha256": "7ca46cc22b7c8f34c455237f5fa3690859ebd0562035c665a514cb2886a7b1a1",
          "sha1": "2a93e418cdf6da9820eebc82c87df01943601a3b",
          "md5": "77487b42b796dabf0aaacb407a4ae4f8"
        }
      ]
    }
  ]
}
