org.gradle.jvmargs=-Xmx4G

# Meta of mod
mod_id=cobe
mod_version=1
mod_name=Cobe
mod_description=geckolib the best!
mod_authors=Akaize
mod_license=MIT
mod_homepage=
mod_issues=
mod_icon=assets/cobe/icon.png

maven_group=v.akfz
archives_base_name=cobe

minecraft_version=1.20.1
mojang_mappings=1.20.1

fabric_loom_version=1.13-SNAPSHOT
fabric_loader_version=0.15.11

forge_version=1.20.1-47.4.20
forge_gradle_version=6.0.53

neoforge_version=2.0.91

mixin_version=0.8.7
mixingradle_version=0.7-SNAPSHOT