{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "cobe-forge-linux",
    "version": "1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cobe-forge-linux-1.jar",
          "url": "cobe-forge-linux-1.jar",
          "size": 298411,
          "sha512": "bbd630a068850dcdbd6821a991aa107ed636f2021e85616f53b605af162516cd381112e65bfc13d47f9ea04a3e29ca852d60e60a94b9538ef07685c28fe5a092",
          "sha256": "b7149492ac3dd75bcdd24d6d27829d549096646a109472885bbd47b9d0fd570f",
          "sha1": "e5feb2ff12028ae857a50c486da547eebcece702",
          "md5": "e4b2ee84c848f642de326860eeeb91f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "v.akfz",
          "module": "aslib-forge",
          "version": {
            "requires": "Dev_1.20.1-SNAPSHOT"
          }
        },
        {
          "group": "org.bytedeco",
          "module": "javacpp",
          "version": {
            "requires": "1.5.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javacpp",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "org.bytedeco",
          "module": "ffmpeg",
          "version": {
            "requires": "6.1.1-1.5.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ffmpeg",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.20_mapped_parchment_2023.09.03-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "cobe-forge-linux-1.jar",
          "url": "cobe-forge-linux-1.jar",
          "size": 298411,
          "sha512": "bbd630a068850dcdbd6821a991aa107ed636f2021e85616f53b605af162516cd381112e65bfc13d47f9ea04a3e29ca852d60e60a94b9538ef07685c28fe5a092",
          "sha256": "b7149492ac3dd75bcdd24d6d27829d549096646a109472885bbd47b9d0fd570f",
          "sha1": "e5feb2ff12028ae857a50c486da547eebcece702",
          "md5": "e4b2ee84c848f642de326860eeeb91f9"
        }
      ]
    }
  ]
}
